CREATE NOTIFICATION INTEGRATION EMAIL_INT
  TYPE = EMAIL
  ENABLED = TRUE
  ALLOWED_RECIPIENTS = ( 'hk69@nyu.edu' )
  DEFAULT_SUBJECT = 'Email Notification';

CREATE DATABASE FILES_DB;
USE DATABASE FILES_DB;
CREATE SCHEMA CSV_FILES;
CREATE STAGE PUBLIC_FILES ENCRYPTION = (TYPE = 'SNOWFLAKE_SSE');



CREATE DATABASE TEST;
create schema TEST_SCHEMA;

create or replace view TEST.TEST_SCHEMA.EMP as select * from data_db.sch.customers; 

